version: '3.4'

services:
  concertbuddy.consoleapp:
    image: skuill/concertbuddyconsoleapp:latest
    tty: true
    stdin_open: true
    container_name: CONCERT_BUDDY
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
    deploy:
      #replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./appsettings.Production.json:/app/appsettings.Production.json
      - ./logs:/app/logs
    networks:
      - common-skuill-network
      
networks:
  common-skuill-network:
    external: true