name: Manual Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_PASSPHRASE }}
          script: |
            cd /srv/docker/concert_buddy
            docker compose pull
            docker compose down
            docker compose up -d
